---
# tasks file for docker-ce-centos
# https://docs.docker.com/engine/installation/linux/centos/
- name: check whether docker-ce has already installed
  command: rpm -q docker-ce
  register: result
  changed_when: no
  failed_when: no
- include: install_docker.yml
  when: result.rc
  static: no
- name: start docker daemon
  service:
    name: docker
    state: started
  when: docker_centos_started
- name: enable docker daemon
  service:
    name: docker
    enabled: yes
  when: docker_centos_enabled
- name: add users to the docker group
  user:
    name: "{{item}}"
    groups: docker
    append: yes
  with_items: "{{docker_centos_users}}"
